# Generated by Django 3.1.7 on 2021-03-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shoppinglist',
        ),
    ]
